"""add_data_date_drop_temperature_index_stats

Revision ID: 257c1fb1b181
Revises: c5a02b8e1f39
Create Date: 2026-05-24 12:04:48.760958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '257c1fb1b181'
down_revision: Union[str, Sequence[str], None] = 'c5a02b8e1f39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('index_stats', sa.Column('data_date', sa.Date(), nullable=True))
    op.drop_column('index_stats', 'temperature')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('index_stats', sa.Column('temperature', mysql.DECIMAL(precision=5, scale=2), nullable=True))
    op.drop_column('index_stats', 'data_date')
    # ### end Alembic commands ###
