"""add akshare_name to indices

Revision ID: 5eb7f49de776
Revises: f7aa8425b00f
Create Date: 2026-05-20 11:38:49.924397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eb7f49de776'
down_revision: Union[str, Sequence[str], None] = 'f7aa8425b00f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indices', sa.Column('akshare_name', sa.String(length=100), nullable=True, comment='akshare接口使用的中文名称'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('indices', 'akshare_name')
    # ### end Alembic commands ###
