"""refactor_indices_add_is_active_drop_akshare_name

Revision ID: d960c3940256
Revises: 257c1fb1b181
Create Date: 2026-05-24 14:29:39.082496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd960c3940256'
down_revision: Union[str, Sequence[str], None] = '257c1fb1b181'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indices', sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否参与数据抓取与前端展示'))
    op.add_column('indices', sa.Column('source', sa.String(length=20), nullable=True, comment='编制机构：csi/sse/hsi 等'))
    op.add_column('indices', sa.Column('currency', sa.String(length=10), nullable=True, comment='计价货币：CNY/HKD/USD'))
    op.add_column('indices', sa.Column('launch_date', sa.Date(), nullable=True, comment='指数发布日期'))
    op.add_column('indices', sa.Column('series', sa.String(length=30), nullable=True, comment='指数系列：size/style/sector/strategy'))
    op.add_column('indices', sa.Column('synced_at', sa.DateTime(), nullable=True, comment='最近一次从理杏仁同步的时间'))
    op.alter_column('indices', 'sector',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='手动维护的中文板块分类',
               existing_nullable=True)
    op.drop_column('indices', 'akshare_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indices', sa.Column('akshare_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True, comment='akshare接口使用的中文名称'))
    op.alter_column('indices', 'sector',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='手动维护的中文板块分类',
               existing_nullable=True)
    op.drop_column('indices', 'synced_at')
    op.drop_column('indices', 'series')
    op.drop_column('indices', 'launch_date')
    op.drop_column('indices', 'currency')
    op.drop_column('indices', 'source')
    op.drop_column('indices', 'is_active')
    # ### end Alembic commands ###
