"""init tables

Revision ID: f7aa8425b00f
Revises: 
Create Date: 2026-05-20 11:37:53.292113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7aa8425b00f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_metrics',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('index_code', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('close', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('pe', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('pb', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index_code', 'date', name='uq_code_date')
    )
    op.create_index('idx_code_date', 'daily_metrics', ['index_code', 'date'], unique=False)
    op.create_table('index_stats',
    sa.Column('index_code', sa.String(length=20), nullable=False),
    sa.Column('pe_percentile', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('pb_percentile', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('pe_min', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('pe_max', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('pe_avg', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('pb_min', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('pb_max', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('pb_avg', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('temperature', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('index_code')
    )
    op.create_table('indices',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('market', sa.Enum('cn', 'hk', 'us'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('indices')
    op.drop_table('index_stats')
    op.drop_index('idx_code_date', table_name='daily_metrics')
    op.drop_table('daily_metrics')
    # ### end Alembic commands ###
